// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechMarket.DataAccess.Data;

#nullable disable

namespace TechMarket.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240316120008_addImageUrlToProductsDb")]
    partial class addImageUrlToProductsDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechMarket.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Victory Products"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Glorious Company"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lion Company"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Phoenix Electronics"
                        });
                });

            modelBuilder.Entity("TechMarket.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Telefon"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Bilgisayar"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Televizyon"
                        });
                });

            modelBuilder.Entity("TechMarket.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Aliquam consectetur diam tellus, vel dictum sapien aliquet vitae.Vestibulum ut libero.",
                            ImageUrl = "",
                            Price = 25000.0,
                            SubCategoryId = 5,
                            Title = "VPhone A12"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus hendrerit libero ut nunc porta venenatis. Mauris scelerisque ligula metus, et.",
                            ImageUrl = "",
                            Price = 45000.0,
                            SubCategoryId = 1,
                            Title = "G-3 Notebook i5 512 GB Gtx-4060"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt laoreet justo pharetra blandit. Integer nec dolor ut dolor congue.",
                            ImageUrl = "",
                            Price = 50000.0,
                            SubCategoryId = 4,
                            Title = "Phoenix PH-4 UHD Smart QLED TV"
                        });
                });

            modelBuilder.Entity("TechMarket.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            DisplayOrder = 1,
                            Name = "Notebook"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DisplayOrder = 2,
                            Name = "Masaüstü Bilgisayarlar"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            DisplayOrder = 1,
                            Name = "Televizyonlar"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            DisplayOrder = 2,
                            Name = "QLED TV"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            DisplayOrder = 1,
                            Name = "Android Modelleri"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            DisplayOrder = 2,
                            Name = "iPhone Modelleri"
                        });
                });

            modelBuilder.Entity("TechMarket.Models.Product", b =>
                {
                    b.HasOne("TechMarket.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechMarket.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("TechMarket.Models.SubCategory", b =>
                {
                    b.HasOne("TechMarket.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
